/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gl_com_jnidemo_JniTest */

#ifndef _Included_gl_com_jnidemo_JniTest
#define _Included_gl_com_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gl_com_jnidemo_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gl_com_jnidemo_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     gl_com_jnidemo_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gl_com_jnidemo_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
